FROM java
MAINTAINER Theo Harkenbusch <Theo@Harkenbusch.com>
ENTRYPOINT ["/usr/bin/java", "-jar", "/usr/share/democoin-node.jar"]

ADD target/lib /usr/share/lib
ADD target/democoin-node.jar /usr/share/democoin-node.jar
